---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  labels:
    app: f-app
spec:
  selector:
    matchLabels:
      app: f-app
  template:
    metadata:
      labels:
        app: f-app
    spec:
      containers:
      - name: front
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: ADDRESS_BACKEND
          value: back-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  labels:
    app: b-app
spec:
  selector:
    matchLabels:
      app: b-app
  template:
    metadata:
      labels:
        app: b-app
    spec:
      containers:
      - name: back
        image: beketov/pythonapp
        ports:
        - containerPort: 9000
        env:
        - name: ADDRESS_DB
          value: postgres-svc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13-alpine
        ports:
          - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: news
---
apiVersion: v1
kind: Service
metadata:
  name: front-svc
  labels:
    app: f-app
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: back-svc
  labels:
    app: b-app
spec:
  type: ClusterIP
  ports:
  - port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
